name-template: "Release $RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"

categories:
  - title: "✨ Features"
    labels:
      - ":sparkles: feature"
  - title: "🛠️ Enhancement"
    labels:
      - ":hammer_and_wrench: enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - ":bug: bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "📝 Update Documentation"
    labels:
      - ":memo: documentation"
  - title: "♻️ Refactoring"
    labels:
      - ":recycle: refactor"

change-template: "- $TITLE @$AUTHOR ([#$NUMBER]($URL))"

change-title-escapes: '\<*_&'

template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: ":sparkles: feature"
    branch:
      - "/^feat(ure)?[/-].+/"
  - label: ":bug: bug"
    branch:
      - "/^fix[/-].+/"
  - label: ":recycle: refactor"
    branch:
      - "/(refactor|refactoring)[/-].+/"
  - label: ":memo: documentation"
    branch:
      - "/doc(umentation)[/-].+/"
    files:
      - "*.md"
  - label: ":hammer_and_wrench: enhancement"
    branch:
      - "/(enhancement|improve)[/-].+/"
  - label: ":rocket: release"
    branch:
      - "/^release[/-].+/"
  - label: ":package: core feature"
    files:
      - "packages/core/**/*.ts"
      - "packages/core/**/*.vue"
